### ISSUE TITLE
For d1mini

### ISSUE THREAD

**Issue by loverboyritesh** [imeszaros/ledclock#12]
can anyone help me with the changes to be made before compiling for Esp8266 boards . just changed it in the platformio_override.ini but getting error while compiling like 
wled00\beeper.h:5:28: fatal error: esp32-hal-ledc.h: No such file or directory

**Comment by semiaquatic** [comment]
Hi. please check the `esp8266` branch.

**Comment by CommittotheIndian** [comment]
wled00\beeper.h:5:28: fatal error: **esp32**-hal-ledc.h: No such file or directory

@loverboyritesh 
This build wasn't designed for the ESP82666. It only works for the ESP32.

https://github.com/imeszaros/ledclock/issues/9#issuecomment-1418220048

**Comment by loverboyritesh** [comment]
Someone commented go and check the branches and again deleted that comment  , i still didnt knew things like branches , it took time for me to explore, find out , anyways thanks to that guy cant but remember the name ...
