### ISSUE TITLE
ESP8266 problems.

### ISSUE THREAD

**Issue by loverboyritesh** [imeszaros/ledclock#13]
tried the esp8266 version but . after connecting to ledclock ap , no pages open on clicking wifi settings and restarts device.even tried to use it in AP mode but all tabs are just not opening ,,,, can anyone try and give a solution ??. even tried a precompiled binary found in the firmware itself but same problem . only can log in to the wifi and 4.3.2.1... Help.

**Comment by imeszaros** [comment]
Sorry, but ESP8266 is not supported by this project. There is an experimental branch for it in this repositoy but I can't help with issues related to ESP8266.
