### ISSUE TITLE
Visual Studio Code Issue

### ISSUE THREAD

**Issue by TMassing85** [imeszaros/ledclock#18]
I have an error in Visual Studio Code with PlatformIO and C++.  I don't know what I did wrong. Can you tell me how? I'm not good with code.

![image](https://github.com/imeszaros/ledclock/assets/37475075/3ded3990-772e-4ff8-b9e3-4fa45067d7ff)

**Comment by imeszaros** [comment]
Hi, please select the `ledclock` environment:

![image](https://github.com/imeszaros/ledclock/assets/144106763/4a1f3e51-b933-46c1-b013-5db43a13e057)

**Comment by TMassing85** [comment]
Same problem both 1.1.0 and 1.3.0.

![image](https://github.com/imeszaros/ledclock/assets/37475075/fdc573f7-5207-4f9c-9b81-df00d19e5ebf)

![image](https://github.com/imeszaros/ledclock/assets/37475075/a82525f6-aebc-49f6-b674-a6bcab170316)

**Comment by imeszaros** [comment]
![image](https://github.com/imeszaros/ledclock/assets/691942/1415e9ff-ffdd-4aa7-b9fc-95a262e477af)

See? This is your problem. I cannot tell you any other way. Change it to "ledclock" end it will compile.

**Comment by TMassing85** [comment]
That is it Thank you.

![image](https://github.com/imeszaros/ledclock/assets/37475075/b88a0f9e-c9df-402f-aeb3-bb44edb7e667)
