### ISSUE TITLE
Hardware for Timer buzz/beeped/speaker

### ISSUE THREAD

**Issue by Zaraxxx** [imeszaros/ledclock#21]
What type of hardware should I buy for adding a buzz/beeped/speaker to the Timer mod?

This is not a feature, it's a question. @imeszaros  can you adjust the Labels accordingly please?

**Comment by imeszaros** [comment]
Any externally driven (i.e. without an internal driver circuit) piezoelectric (and not electrodynamic!) buzzer would do. I used this one:

https://www.hestore.hu/prod_getfile.php?id=11849

**Comment by Zaraxxx** [comment]
Thank you
