### ISSUE TITLE
Connecting to wemos

### ISSUE THREAD

**Issue by Muliku82** [imeszaros/ledclock#3]
Hey.
I have successfully uploaded your fork to my wemos D1 mini, but when I connect to led AP, I don't get a interface but something ups downloading. Can you help me

**Comment by imeszaros** [comment]
Hey @Muliku82 , wemos D1 is ESP8266, right? Did you upload the firmware from the `esp8266` branch? My fork only supports ESP32, but there is an experimental version on the `esp8266` branch that should work. See #1

**Comment by Muliku82** [comment]
Yes, i used the 8266 branch.Holen Sie sich Outlook für Android
