### ISSUE TITLE
Board not supported error

### ISSUE THREAD

**Issue by LNT00** [imeszaros/ledclock#6]
### What happened?

I have three boards, two esp8266 not working and one esp32 which works, I get the board not supported message:
- D1 MINI V4.0.0 - dosn't work
- NodeMcu V3 ESP8266 - doesn't work
- ESP32-WROVER - works

![board_not_supported](https://user-images.githubusercontent.com/32333032/198874955-df3e071d-62a8-449c-a735-1e38abf4facf.jpg)

What's interesting is that all three work when trying to upload the Aircoookie/WLED firmware.

Any idea how to get around this?

Thanks!

### To Reproduce Bug

upload firmware using https://imeszaros.github.io/ledclock/

### Expected Behavior

upload works

### Install Method

Binary from WLED.me

### What version of WLED?

1.2.0

### Which microcontroller/board are you seeing the problem on?

ESP8266, ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CommittotheIndian** [comment]
It's not a bug. The main branch is designed for the ESP32![image](https://user-images.githubusercontent.com/60204668/198881061-de9f7959-1207-4d67-8204-9fccb4c73dba.jpeg)

Try this branch for the 8266.
