### ISSUE TITLE
Sound reactive

### ISSUE THREAD

**Issue by TysTies** [imeszaros/ledclock#7]
**Could you merge you WLED with this fork? https://github.com/atuline/WLED/releases/ (the official SR Fork)**
I would also like to be able to change the length of segments in settings rather than have to reflash. 
Thanks for making this awesome fork! also, when is the next update coming out?

**Comment by imeszaros** [comment]
Version 1.3.0 has upgraded to WLED 0.14.1 so audio reactive is now supported: https://kno.wled.ge/advanced/audio-reactive/

Compile the firmware with the necessary usermod enabled.
